# Generated by Django 4.2.5 on 2023-09-21 20:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PicastroUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.CharField(max_length=25, unique=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=25)),
                ("phone_no", models.CharField(max_length=16)),
                ("isEmailVerified", models.BooleanField(default=False)),
                ("isPhoneVerified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("subcriptionsExpiry", models.DateTimeField(auto_now_add=True)),
                (
                    "profileImage",
                    models.ImageField(
                        blank=True,
                        default="profileImages/sampleuserbig.png",
                        upload_to="profileImages/",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=50)),
                (
                    "userDescription",
                    models.TextField(blank=True, default="", max_length=200),
                ),
                (
                    "genderIdentifier",
                    models.TextField(blank=True, default="divers", max_length=10),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "thumbnail",
                    models.ImageField(default="", editable=False, upload_to="resize/"),
                ),
                ("imageDescription", models.TextField(max_length=2000)),
                ("imageCategory", models.TextField(default="others")),
                ("astroNameShort", models.TextField(max_length=10)),
                ("astroName", models.TextField(max_length=50)),
                ("award", models.TextField(default="None")),
                ("exposureTime", models.TextField(max_length=8)),
                ("moonPhase", models.TextField(max_length=4)),
                ("cloudCoverage", models.TextField(max_length=4)),
                ("bortle", models.TextField(max_length=1)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("aspectRatio", models.FloatField(default=1, editable=False)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StarCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starCampName", models.TextField(unique=True)),
                ("starCampLocation", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SavedImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="picastro.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setName", models.CharField(default="DEFAULT VALUE", max_length=140)),
                ("telescopeName", models.TextField()),
                ("cameraName", models.TextField()),
                ("guideCameraName", models.TextField()),
                ("offAxisguidecamera", models.TextField()),
                ("filterWheelName", models.TextField()),
                ("filters", models.TextField()),
                ("barlowLense", models.TextField()),
                ("otherEquipment", models.TextField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="picastro.post"
                    ),
                ),
            ],
        ),
    ]
