# Generated by Django 4.2.3 on 2023-07-30 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "thumbnail",
                    models.ImageField(default="", editable=False, upload_to="resize/"),
                ),
                ("imageDescription", models.TextField()),
                ("imageCategory", models.TextField(default="others")),
                ("astroNameShort", models.TextField()),
                ("astroName", models.TextField()),
                ("award", models.TextField(default="None")),
                ("exposureTime", models.TextField()),
                ("moonPhase", models.TextField()),
                ("cloudCoverage", models.TextField()),
                ("bortle", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StarCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starCampName", models.TextField(unique=True)),
                ("starCampLocation", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriptionsPlan", models.TextField()),
                ("subscriptionsDuration", models.DurationField()),
                (
                    "subscriptionsPrice",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profileImage",
                    models.ImageField(
                        default="profileImages/sampleuserbig.png",
                        upload_to="profileImages/",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("subcriptionsExpiry", models.DateTimeField(auto_now_add=True)),
                ("isEmailVerified", models.BooleanField()),
                ("userDescription", models.TextField()),
                ("genderIdentifier", models.TextField(default="divers")),
                (
                    "starCampId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="picastro.starcamp",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="picastro.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setName", models.CharField(default="DEFAULT VALUE", max_length=140)),
                ("telescopeName", models.TextField()),
                ("cameraName", models.TextField()),
                ("guideCameraName", models.TextField()),
                ("offAxisguidecamera", models.TextField()),
                ("filterWheelName", models.TextField()),
                ("filters", models.TextField()),
                ("barlowLense", models.TextField()),
                ("otherEquipment", models.TextField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="picastro.post"
                    ),
                ),
            ],
        ),
    ]
