# Generated by Django 4.1.7 on 2023-09-30 21:36

from django.db import migrations
import picastro.models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='picastrouser',
            managers=[
                ('objects', picastro.models.PicastroUserManager()),
            ],
        ),
    ]
