# Generated by Django 4.1.7 on 2023-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageURL',
            field=models.TextField(),
        ),
    ]
