# Generated by Django 4.1.7 on 2023-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0002_delete_subscription_remove_userprofile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="astroName",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="astroNameShort",
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name="post",
            name="bortle",
            field=models.TextField(max_length=1),
        ),
        migrations.AlterField(
            model_name="post",
            name="cloudCoverage",
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name="post",
            name="exposureTime",
            field=models.TextField(max_length=7),
        ),
        migrations.AlterField(
            model_name="post",
            name="imageDescription",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="moonPhase",
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
