# Generated by Django 4.1.7 on 2023-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0002_alter_post_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starCampName', models.TextField()),
                ('starCamplocation', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
