# Generated by Django 4.1.7 on 2023-12-22 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0002_alter_picastrouser_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picastrouser",
            old_name="subcriptionsExpiry",
            new_name="subscriptionExpiry",
        ),
    ]
