# Generated by Django 4.1.7 on 2023-12-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0003_rename_subcriptionsexpiry_picastrouser_subscriptionexpiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="picastrouser",
            name="payment_checkout_id",
            field=models.CharField(default="", max_length=500),
        ),
    ]
