# Generated by Django 4.1.7 on 2023-03-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0003_starcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.URLField()),
                ('userName', models.TextField()),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('subcriptionsExpiry', models.DateTimeField(auto_now_add=True)),
                ('isEmailVerified', models.TextField()),
                ('userCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('userDescription', models.TextField()),
                ('starCampId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picastro.starcamp')),
            ],
        ),
    ]
