# Generated by Django 4.1.7 on 2023-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0003_alter_post_astroname_alter_post_astronameshort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aspectRatio',
            field=models.FloatField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genderIdentifier',
            field=models.TextField(default='divers', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userDescription',
            field=models.TextField(default='', max_length=200),
        ),
    ]
