# Generated by Django 4.1.7 on 2023-03-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescopeName', models.TextField()),
                ('cameraName', models.TextField()),
                ('guideCameraName', models.BooleanField()),
                ('offAxisguidecamera', models.TextField()),
                ('filterWheelName', models.TextField()),
                ('filters', models.TextField()),
                ('barlowLense', models.TextField()),
                ('otherEquipment', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picastro.user')),
            ],
        ),
    ]
