# Generated by Django 4.1.7 on 2023-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "picastro",
            "0004_post_aspectratio_alter_userprofile_genderidentifier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="exposureTime",
            field=models.TextField(max_length=8),
        ),
        migrations.AlterField(
            model_name="post",
            name="imageDescription",
            field=models.TextField(max_length=2000),
        ),
    ]
