# Generated by Django 4.1.7 on 2023-03-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0005_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageissaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageIsSaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picastro.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picastro.user')),
            ],
        ),
    ]
