# Generated by Django 4.1.7 on 2023-03-05 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picastro', '0006_imageissaved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcriptionsPlan', models.TextField()),
                ('subcriptionsDuration', models.DurationField()),
                ('subcriptionsPrice', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('subcriptionsExpiry', models.DateTimeField(auto_now_add=True)),
                ('isEmailVerified', models.BooleanField()),
                ('userDescription', models.TextField()),
                ('starCampId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picastro.starcamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='setName',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='guideCameraName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageissaved',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
