# Generated by Django 4.1.7 on 2023-03-06 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picastro', '0007_subscription_userprofile_equipment_setname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starcamp',
            old_name='starCamplocation',
            new_name='starCampLocation',
        ),
        migrations.CreateModel(
            name='savedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picastro.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
