# Generated by Django 4.1.7 on 2023-03-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0008_rename_starcamplocation_starcamp_starcamplocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageURL',
            field=models.URLField(),
        ),
    ]
