# Generated by Django 4.1.7 on 2023-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0009_alter_post_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='images/'),
        ),
    ]
