# Generated by Django 4.1.7 on 2023-03-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0009_alter_post_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genderIdentifier',
            field=models.TextField(default='divers'),
        ),
        migrations.AlterField(
            model_name='starcamp',
            name='starCampName',
            field=models.TextField(unique=True),
        ),
    ]
