# Generated by Django 4.1.7 on 2023-03-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0010_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageURL',
        ),
    ]
