# Generated by Django 4.1.7 on 2023-03-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0010_userprofile_genderidentifier_and_more'),
        ('picastro', '0011_remove_post_imageurl'),
    ]

    operations = [
    ]
