# Generated by Django 4.1.7 on 2023-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0012_merge_20230309_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageURL',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
