# Generated by Django 4.1.7 on 2023-03-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picastro', '0013_post_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageURL',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
