# Generated by Django 4.1.7 on 2023-03-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picastro", "0014_remove_post_imageurl_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imageCategory",
            field=models.TextField(default=""),
        ),
    ]
