# Generated by Django 4.1.7 on 2023-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picastro", "0015_post_imagecategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="award",
            field=models.TextField(default="None"),
        ),
        migrations.AlterField(
            model_name="post",
            name="imageIsSaved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="leadingLight",
            field=models.BooleanField(default=False),
        ),
    ]
