# Generated by Django 4.1.7 on 2023-03-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picastro", "0016_alter_post_award_alter_post_imageissaved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profileImage",
            field=models.ImageField(
                default="sampleuserbig.png", upload_to="profileImages/"
            ),
        ),
    ]
