# Generated by Django 4.1.7 on 2023-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picastro", "0017_userprofile_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profileImage",
            field=models.ImageField(
                default="profileImages/sampleuserbig.png", upload_to="profileImages/"
            ),
        ),
    ]
