# Generated by Django 4.1.7 on 2023-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0018_alter_userprofile_profileimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(default="", editable=False, upload_to="resized/"),
        ),
    ]
