# Generated by Django 4.1.7 on 2023-07-26 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0019_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commenter_name",
            new_name="commenter",
        ),
    ]
