# Generated by Django 4.1.7 on 2023-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0019_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                default="resize/kaboom-scale.jpg", editable=False, upload_to="resize/"
            ),
        ),
    ]
