# Generated by Django 4.1.7 on 2023-04-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0020_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(editable=False, upload_to="resize/"),
        ),
    ]
