# Generated by Django 4.1.7 on 2023-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0024_remove_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                default=models.ImageField(upload_to="images/"),
                editable=False,
                upload_to="resize/",
            ),
        ),
    ]
