# Generated by Django 4.1.7 on 2023-04-05 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0025_post_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thumbnail",
        ),
    ]
