# Generated by Django 4.1.7 on 2023-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0026_remove_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(default="", editable=False, upload_to="resize/"),
        ),
    ]
