# Generated by Django 4.1.7 on 2023-04-06 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0027_post_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedimages",
            old_name="imageId",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="savedimages",
            old_name="userId",
            new_name="user",
        ),
        migrations.DeleteModel(
            name="Imageissaved",
        ),
    ]
