# Generated by Django 4.1.7 on 2023-04-26 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0028_rename_imageid_savedimages_post_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subcriptionsDuration",
            new_name="subscriptionsDuration",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="subcriptionsPlan",
            new_name="subscriptionsPlan",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="subcriptionsPrice",
            new_name="subscriptionsPrice",
        ),
        migrations.RemoveField(
            model_name="post",
            name="leadingLight",
        ),
    ]
