# Generated by Django 4.1.7 on 2023-04-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0028_rename_imageid_savedimages_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
