# Generated by Django 4.1.7 on 2023-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "picastro",
            "0029_rename_subcriptionsduration_subscription_subscriptionsduration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="leadingLight",
            field=models.BooleanField(default=False),
        ),
    ]
