# Generated by Django 4.1.7 on 2023-04-27 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0030_post_leadinglight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="leadingLight",
        ),
    ]
