# Generated by Django 4.1.7 on 2023-05-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0031_remove_post_leadinglight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="isEmailVerified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="starCampId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="picastro.starcamp",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="userDescription",
            field=models.TextField(default=""),
        ),
    ]
