# Generated by Django 4.1.7 on 2023-06-04 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0032_alter_userprofile_isemailverified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="imageIsSaved",
        ),
        migrations.RemoveField(
            model_name="post",
            name="starCamp",
        ),
    ]
