# Generated by Django 4.1.7 on 2023-06-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0033_remove_post_imageissaved_remove_post_starcamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="starCampId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="picastro.starcamp"
            ),
        ),
    ]
