# Generated by Django 4.1.7 on 2023-06-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0034_alter_userprofile_starcampid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="starCampId",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="picastro.starcamp",
            ),
        ),
    ]
