# Generated by Django 4.1.7 on 2023-06-11 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0036_alter_userprofile_starcampid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
