# Generated by Django 4.1.7 on 2023-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0038_remove_userprofile_id_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="savedimages",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_post_combination"
            ),
        ),
    ]
