# Generated by Django 4.1.7 on 2023-07-06 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picastro", "0039_savedimages_unique_user_post_combination"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="savedimages",
            name="unique_user_post_combination",
        ),
    ]
