# Generated by Django 4.1.7 on 2023-03-29 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("imageDescription", models.TextField()),
                ("imageCategory", models.TextField(default="")),
                ("astroNameShort", models.TextField()),
                ("astroName", models.TextField()),
                ("imageIsSaved", models.BooleanField(default=False)),
                ("award", models.TextField(default="None")),
                ("exposureTime", models.TextField()),
                ("moonPhase", models.TextField()),
                ("cloudCoverage", models.TextField()),
                ("bortle", models.TextField()),
                ("starCamp", models.TextField()),
                ("leadingLight", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_post_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StarCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starCampName", models.TextField(unique=True)),
                ("starCampLocation", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcriptionsPlan", models.TextField()),
                ("subcriptionsDuration", models.DurationField()),
                (
                    "subcriptionsPrice",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("subcriptionsExpiry", models.DateTimeField(auto_now_add=True)),
                ("isEmailVerified", models.BooleanField()),
                ("userDescription", models.TextField()),
                ("genderIdentifier", models.TextField(default="divers")),
                (
                    "starCampId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="picastro_web.starcamp",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="savedImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="picastro_web.post",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savedImages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageIsSaved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageIsSaved",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="picastro_web.post",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_imageIsSaved_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setName", models.CharField(default="DEFAULT VALUE", max_length=140)),
                ("telescopeName", models.TextField()),
                ("cameraName", models.TextField()),
                ("guideCameraName", models.TextField()),
                ("offAxisguidecamera", models.TextField()),
                ("filterWheelName", models.TextField()),
                ("filters", models.TextField()),
                ("barlowLense", models.TextField()),
                ("otherEquipment", models.TextField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_equipment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
