# Generated by Django 4.1.7 on 2023-03-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("picastro_web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="imageissaved",
            name="imageIsSaved",
        ),
        migrations.RemoveField(
            model_name="imageissaved",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="post",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="savedimages",
            name="imageId",
        ),
        migrations.RemoveField(
            model_name="savedimages",
            name="userId",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="starCampId",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="ImageIsSaved",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="savedImages",
        ),
        migrations.DeleteModel(
            name="StarCamp",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
